# Generated by Django 5.2.12 on 2026-03-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tactics_opportunities_count", models.IntegerField(default=0)),
                ("tactics_missed_count", models.IntegerField(default=0)),
                ("avg_time_per_move", models.FloatField(blank=True, null=True)),
                ("median_time_per_move", models.FloatField(blank=True, null=True)),
                ("max_time_per_move", models.FloatField(blank=True, null=True)),
                ("total_time_used", models.FloatField(blank=True, null=True)),
                ("time_pressure_moves_count", models.IntegerField(default=0)),
                ("analyzed_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="MoveTimeCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_category",
                    models.CharField(
                        choices=[
                            ("instant", "Instant"),
                            ("quick", "Quick"),
                            ("normal", "Normal"),
                            ("considered", "Considered"),
                            ("long_think", "Long Think"),
                        ],
                        max_length=15,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TacticsOpportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tactic_type",
                    models.CharField(
                        choices=[
                            ("fork", "Fork"),
                            ("pin", "Pin"),
                            ("skewer", "Skewer"),
                        ],
                        max_length=10,
                    ),
                ),
                ("missed", models.BooleanField()),
                ("best_move_uci", models.CharField(max_length=5)),
                (
                    "played_move_uci",
                    models.CharField(blank=True, default="", max_length=5),
                ),
                ("attacking_piece", models.CharField(max_length=2)),
                ("attacking_square", models.CharField(max_length=2)),
                ("targets", models.JSONField(default=list)),
                ("fen", models.TextField()),
                ("description", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["game", "move__ply"],
            },
        ),
    ]
