# Generated by Django 5.2.12 on 2026-03-07 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analytics", "0001_initial"),
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameanalysis",
            name="game",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analysis",
                to="games.game",
            ),
        ),
        migrations.AddField(
            model_name="movetimecategory",
            name="move",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="time_category",
                to="games.move",
            ),
        ),
        migrations.AddField(
            model_name="tacticsopportunity",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tactics_opportunities",
                to="games.game",
            ),
        ),
        migrations.AddField(
            model_name="tacticsopportunity",
            name="move",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tactics_opportunities",
                to="games.move",
            ),
        ),
    ]
