# Generated by Django 5.2.12 on 2026-03-07 16:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("lichess", "Lichess"), ("pgn_import", "PGN Import")],
                        max_length=20,
                    ),
                ),
                (
                    "lichess_game_id",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "white_username",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "black_username",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "user_color",
                    models.CharField(
                        choices=[("white", "White"), ("black", "Black")], max_length=5
                    ),
                ),
                ("white_rating", models.IntegerField(blank=True, null=True)),
                ("black_rating", models.IntegerField(blank=True, null=True)),
                ("user_rating", models.IntegerField(blank=True, null=True)),
                ("opponent_rating", models.IntegerField(blank=True, null=True)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("white", "White wins"),
                            ("black", "Black wins"),
                            ("draw", "Draw"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "user_result",
                    models.CharField(
                        choices=[("win", "Win"), ("loss", "Loss"), ("draw", "Draw")],
                        max_length=4,
                    ),
                ),
                (
                    "termination",
                    models.CharField(
                        choices=[
                            ("checkmate", "Checkmate"),
                            ("resignation", "Resignation"),
                            ("timeout", "Timeout"),
                            ("draw", "Draw"),
                            ("stalemate", "Stalemate"),
                            ("repetition", "Repetition"),
                            ("insufficient", "Insufficient material"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "time_control",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "time_control_category",
                    models.CharField(
                        choices=[
                            ("ultrabullet", "UltraBullet"),
                            ("bullet", "Bullet"),
                            ("blitz", "Blitz"),
                            ("rapid", "Rapid"),
                            ("classical", "Classical"),
                            ("correspondence", "Correspondence"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("initial_time", models.IntegerField(blank=True, null=True)),
                ("increment", models.IntegerField(default=0)),
                (
                    "opening_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "opening_eco",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("pgn", models.TextField()),
                ("played_at", models.DateTimeField()),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                ("analysis_complete", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-played_at"],
            },
        ),
        migrations.CreateModel(
            name="Move",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ply", models.PositiveIntegerField()),
                ("move_number", models.PositiveIntegerField()),
                (
                    "color",
                    models.CharField(
                        choices=[("white", "White"), ("black", "Black")], max_length=5
                    ),
                ),
                ("san", models.CharField(max_length=10)),
                ("uci", models.CharField(max_length=5)),
                ("fen_before", models.TextField()),
                ("fen_after", models.TextField()),
                ("clock_time_remaining", models.FloatField(blank=True, null=True)),
                ("time_spent", models.FloatField(blank=True, null=True)),
            ],
            options={
                "ordering": ["ply"],
            },
        ),
    ]
