# Generated by Django 5.2.12 on 2026-03-07 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("games", "0001_initial"),
        ("imports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="pgn_import",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="games",
                to="imports.pgnimport",
            ),
        ),
    ]
