# Generated by Django 5.2.12 on 2026-03-07 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("games", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="games",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="move",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="moves",
                to="games.game",
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["user", "-played_at"], name="games_game_user_id_b6cfd5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["user", "user_result"], name="games_game_user_id_713809_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["user", "time_control_category"],
                name="games_game_user_id_d547c8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["user", "user_color"], name="games_game_user_id_6d2eb0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="game",
            constraint=models.UniqueConstraint(
                condition=models.Q(("lichess_game_id__isnull", False)),
                fields=("user", "lichess_game_id"),
                name="unique_user_lichess_game",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="move",
            unique_together={("game", "ply")},
        ),
    ]
