# Generated by Django 4.2.7 on 2023-11-28 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=50, unique=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('time_control', models.CharField(max_length=10)),
                ('time_class', models.CharField(choices=[('LIVE', 'Live'), ('DAILY', 'Daily')], max_length=5)),
                ('opening', models.CharField(blank=True, max_length=255, null=True)),
                ('result', models.CharField(blank=True, max_length=5, null=True)),
                ('outcome', models.CharField(blank=True, max_length=255, null=True)),
                ('white_elo', models.SmallIntegerField()),
                ('white_accuracy', models.FloatField(blank=True, null=True)),
                ('black_elo', models.SmallIntegerField()),
                ('black_accuracy', models.FloatField(blank=True, null=True)),
                ('black_player', models.ForeignKey(db_column='black_player', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_black', to='players.player', to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('url', models.URLField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('REGISTRATION', 'Registration'), ('IN_PROGRESS', 'In Progress'), ('FINISHED', 'Finished')], max_length=15)),
                ('finish_time', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(max_length=100)),
                ('rules', models.CharField(max_length=50)),
                ('time_class', models.CharField(choices=[('LIVE', 'Live'), ('DAILY', 'Daily')], max_length=5)),
                ('time_control', models.CharField(max_length=10)),
                ('is_rated', models.BooleanField(default=True)),
                ('is_official', models.BooleanField(default=False)),
                ('is_invite_only', models.BooleanField(default=False)),
                ('initial_group_size', models.IntegerField()),
                ('user_advance_count', models.SmallIntegerField()),
                ('use_tiebreak', models.BooleanField(default=True)),
                ('allow_vacation', models.BooleanField(default=False)),
                ('winner_places', models.SmallIntegerField(default=1)),
                ('registered_user_count', models.IntegerField()),
                ('games_per_opponent', models.SmallIntegerField()),
                ('total_rounds', models.SmallIntegerField()),
                ('concurrent_games_per_opponent', models.SmallIntegerField()),
                ('creator', models.ForeignKey(blank=True, db_column='creator', null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.player', to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_num', models.SmallIntegerField()),
                ('move', models.CharField(max_length=10)),
                ('color', models.CharField(choices=[('BLACK', 'Black'), ('WHITE', 'White')], max_length=5)),
                ('game_id', models.ForeignKey(db_column='game_id', on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='games.game', to_field='game_id')),
                ('player', models.ForeignKey(blank=True, db_column='player', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moves', to='players.player', to_field='username')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='tournament',
            field=models.ForeignKey(blank=True, db_column='tournament', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments', to='games.tournament'),
        ),
        migrations.AddField(
            model_name='game',
            name='white_player',
            field=models.ForeignKey(db_column='white_player', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_white', to='players.player', to_field='username'),
        ),
        migrations.AddConstraint(
            model_name='move',
            constraint=models.UniqueConstraint(fields=('game_id', 'move_num', 'color'), name='unique_game_id_move_num_color_constraint'),
        ),
    ]
