# Generated by Django 5.1.1 on 2024-09-20 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='lastMoveAt',
            new_name='last_move_at',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='opening_id',
            new_name='opening',
        ),
    ]
