# Generated by Django 5.1.1 on 2024-09-20 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_rename_lastmoveat_game_last_move_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='move',
            old_name='game_id',
            new_name='game',
        ),
    ]
