# Generated by Django 5.1.1 on 2024-09-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_rename_game_id_move_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.CharField(blank=True, choices=[('black', 'Black'), ('white', 'White')], max_length=5, null=True),
        ),
    ]
