# Generated by Django 5.1.1 on 2024-09-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_game_winner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='move',
            old_name='move_notation',
            new_name='move',
        ),
        migrations.AlterField(
            model_name='move',
            name='clock_end',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='move',
            name='clock_start',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='move',
            name='time_spent',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
