# Generated by Django 4.2.7 on 2023-11-28 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(db_column='code', max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('url', models.URLField(unique=True)),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(choices=[('FM', 'FIDE Master'), ('IM', 'International Master'), ('NM', 'National Master'), ('GM', 'Grandmaster'), ('CM', 'Candidate Master'), ('WGM', 'Woman Grandmaster'), ('WIM', 'Woman International Master'), ('WFM', 'Woman FIDE Master'), ('WCM', 'Woman Candidate Master'), ('WNM', 'Woman National Master'), ('AGM', 'Arena Grandmaster'), ('AIM', 'Arena International Master'), ('AFM', 'Arena FIDE Master'), ('ACM', 'Arena Candidate Master'), ('ANM', 'Arena National Master'), ('IA', 'International Arbiter'), ('FA', 'FIDE Arbiter'), ('FST', 'FIDE Senior Trainer'), ('FT', 'FIDE Trainer'), ('FI', 'FIDE Instructor'), ('NI', 'National Instructor'), ('DI', 'Developmental Instructor'), ('FIO', 'FIDE International Organizer')], max_length=3)),
                ('status', models.CharField(choices=[('closed', 'Closed'), ('closed:fair_play_violations', 'Closed: Fair Play Violations'), ('basic', 'Basic'), ('premium', 'Premium'), ('mod', 'Moderator'), ('staff', 'Staff')], max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('fide_rating', models.SmallIntegerField(blank=True, null=True)),
                ('country', models.ForeignKey(blank=True, db_column='country', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='players.country')),
            ],
        ),
    ]
